services:
  # Redis Database
  redis:
    image: redis:7-alpine
    container_name: redis-db-hub
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - mcp-network

  # MCP Redis Server (From DockerHub)
  mcp-redis:
    image: toolbox-images/couchbase:latest
    container_name: mcp-redis-server-hub
    environment:
      DB_TYPE: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TOOLBOX_LOG_LEVEL: info
    ports:
      - "5003:5000"
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - mcp-network
    restart: unless-stopped

networks:
  mcp-network:
    driver: bridge