services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db-local
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - mcp-network

  # MCP PostgreSQL Server (Built Locally)
  mcp-postgres:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TOOLBOX_VERSION: 0.9.0
    container_name: mcp-postgres-server-local
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: testdb
      DB_USER: testuser
      DB_PASSWORD: testpass
      DB_SSL_MODE: prefer
      TOOLBOX_LOG_LEVEL: info
    ports:
      - "5001:5000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - mcp-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  mcp-network:
    driver: bridge