services:
  # Neo4j Database
  neo4j:
    image: neo4j:5-community
    container_name: neo4j-db-local
    environment:
      NEO4J_AUTH: neo4j/testpass
      NEO4J_PLUGINS: '["apoc"]'
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "testpass", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - mcp-network

  # MCP Neo4j Server (Built Locally)
  mcp-neo4j:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TOOLBOX_VERSION: 0.9.0
    container_name: mcp-neo4j-server-local
    environment:
      DB_TYPE: neo4j
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: testpass
      NEO4J_DATABASE: neo4j
      TOOLBOX_LOG_LEVEL: info
    ports:
      - "5005:5000"
    depends_on:
      neo4j:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - mcp-network
    restart: unless-stopped

volumes:
  neo4j_data:
    driver: local

networks:
  mcp-network:
    driver: bridge