name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build-dockerfiles:
    name: Build Dockerfiles
    runs-on: ubuntu-latest
    strategy:
      matrix:
        database: [postgres, mysql, redis, sqlite]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          cd databases/${{ matrix.database }}
          docker build -f Dockerfile -t mcp-${{ matrix.database }}:latest .

      - name: Test image runs
        run: |
          docker run --rm mcp-${{ matrix.database }}:latest --help || true

  test-mcp-functionality:
    name: Test MCP Functionality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        database: [postgres, mysql, redis]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run MCP functionality tests
        run: |
          python tests/test_mcp_functionality.py
