name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    name: Build Dockerfiles
    runs-on: ubuntu-latest
    strategy:
      matrix:
        database: [postgres, mysql, redis, sqlite, alloydb, bigquery, firestore, neo4j, redshift, snowflake, spanner, sqlserver, supabase]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -f Dockerfile.${{ matrix.database }} -t mcp-${{ matrix.database }}:latest .

      - name: Test image runs
        run: |
          docker run --rm mcp-${{ matrix.database }}:latest --help || true
